# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'FieldsReact' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FieldsReact
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
pod 'Firebase/Storage', '~> 5.3.0'




  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'



end

# Auth0 Lock

pod 'Lock', '~> 1.26'
pod 'Lock/TouchID'
pod 'Lock/SMS'
pod 'Lock/Email'
