export const welcome = "Welcome to Fields! Let's create an account for you!";
export const welcome_back = 'Welcome back!'
export const username = 'Username';
export const email = 'Email';
export const login = 'Login';
export const signup = 'Sign Up';
export const password = 'Password';
export const already_have_an_account = 'Already have an account? Log in Here';
export const dont_have_an_account = "Don't have an account? Sign Up here"
export const name = 'Name';
export const please_enter_valid_email = "Please enter valid email";
export const please_enter_username = "Please enter username";
export const please_enter_password = "Please enter password over 6 characters long";
export const by_signing_up_you = 'By signing up you agree to our';
export const terms = 'Terms'
